static_resources:
  listeners:
    - name: https_gateway_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 443

      listener_filters:
        - name: envoy.filters.listener.tls_inspector
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector

      filter_chains:

        ########################################################
        # *.toefl.wiki
        ########################################################
        - filter_chain_match:
            server_names: ["*.toefl.wiki"]

          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                alpn_protocols: ["h2", "http/1.1"]
                tls_certificates:
                  - certificate_chain:
                      filename: /app/envoy/cert/toefl.wiki/server.pem
                    private_key:
                      filename: /app/envoy/cert/toefl.wiki/server.key

          filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: toefl_https
                use_remote_address: true
                xff_num_trusted_hops: 1

                route_config:
                  name: toefl_routes
                  virtual_hosts:
                    - name: auth_server_toefl
                      domains: ["auth-server.toefl.wiki"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: auth_server_toefl_backend
                            host_rewrite_literal: 127.0.0.1

                    - name: my_toefl
                      domains: ["my.toefl.wiki"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: my_toefl_backend
                            host_rewrite_literal: 127.0.0.1

                    - name: app_toefl
                      domains: ["app.toefl.wiki"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: app_toefl_backend
                            host_rewrite_literal: 127.0.0.1

                http_filters:
                  - name: envoy.filters.http.local_ratelimit
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                      stat_prefix: toefl_rl
                      token_bucket:
                        max_tokens: 100
                        tokens_per_fill: 50
                        fill_interval: 1s
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

        ########################################################
        # *.cpns.app
        ########################################################
        - filter_chain_match:
            server_names: ["*.cpns.app"]

          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                alpn_protocols: ["h2", "http/1.1"]
                tls_certificates:
                  - certificate_chain:
                      filename: /app/envoy/cert/cpns.app/server.pem
                    private_key:
                      filename: /app/envoy/cert/cpns.app/server.key

          filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: cpns_https
                use_remote_address: true
                xff_num_trusted_hops: 1

                route_config:
                  name: cpns_routes
                  virtual_hosts:
                    - name: auth_server_cpns
                      domains: ["auth-server.cpns.app"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: auth_server_cpns_backend
                            host_rewrite_literal: 127.0.0.1

                    - name: my_cpns
                      domains: ["my.cpns.app"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: my_cpns_backend
                            host_rewrite_literal: 127.0.0.1

                    - name: platform_cpns
                      domains: ["platform.cpns.app"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: platform_cpns_backend
                            host_rewrite_literal: 127.0.0.1

                http_filters:
                  - name: envoy.filters.http.local_ratelimit
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                      stat_prefix: cpns_rl
                      token_bucket:
                        max_tokens: 100
                        tokens_per_fill: 50
                        fill_interval: 1s
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  ############################################################
  # CLUSTERS â€” STATIC + REQUIRED cluster_name
  ############################################################
  clusters:
    - name: auth_server_toefl_backend
      connect_timeout: 5s
      type: static
      lb_policy: round_robin
      load_assignment:
        cluster_name: auth_server_toefl_backend
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8080

    - name: my_toefl_backend
      connect_timeout: 5s
      type: static
      lb_policy: round_robin
      load_assignment:
        cluster_name: my_toefl_backend
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 3001

    - name: app_toefl_backend
      connect_timeout: 5s
      type: static
      lb_policy: round_robin
      load_assignment:
        cluster_name: app_toefl_backend
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 3002

    - name: auth_server_cpns_backend
      connect_timeout: 5s
      type: static
      lb_policy: round_robin
      load_assignment:
        cluster_name: auth_server_cpns_backend
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 3003

    - name: my_cpns_backend
      connect_timeout: 5s
      type: static
      lb_policy: round_robin
      load_assignment:
        cluster_name: my_cpns_backend
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 3004

    - name: platform_cpns_backend
      connect_timeout: 5s
      type: static
      lb_policy: round_robin
      load_assignment:
        cluster_name: platform_cpns_backend
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 3005
